### ISSUE TITLE
Read CSV Headers in Template

### ISSUE THREAD

**Issue by herculosh** [farling42/obsidian-import-json#35]
Hi, 

I would like to read all Column-Headers in the CSV and list each column and field as Tag in the Template. 
How can I read the inside the the Handlebar template? 

TIA

**Comment by farling42** [comment]
This is just a general Handlebars question, rather than a specific issue to do with this plug-in.

You can use the following to get the list of column names that appear in the CSV file:

```
{{#each this}} {{{@key}}}: {{{this}}}
{{/each}}
```

(I used three {{{ around the internal variables in order to ensure that HTML escaping of special characters was NOT performed.
