### ISSUE TITLE
REPLACE not deleting previous files.

### ISSUE THREAD

**Issue by buttonpushertv** [farling42/obsidian-import-json#69]
Using v0.36.1 of the importer and the latest version of Obsidian (on Windows), importing from JSON file with the REPLACE option selected, it shows an error in the console that each file it attempts to create already exists and fails to create new versions of the files to overwrite the previous versions.

At first I thought this may be related to some other plugin I had installed, but I created a brand new vault and only installed the JSON/CSV Importer plugin today and attempted to run an import two times, with the REPLACE option chosen. It imported and created the files on the first pass with no errors. When I ran the import a second time, it returned the error that they each already existed and did not create new files.

**Comment by farling42** [comment]
At some point in the updates to Obsidian.md, they changed the vault to always expect to use "/" as the folder separator instead of using the operating system's underlying separator (which would be defined by the JS variable `path.sep`).

Version 0.36.2 contains an update to hard-code "/" to be used when accessing the vault.
