### ISSUE TITLE
Can multiple values in one cell work?

### ISSUE THREAD

**Issue by ooker777** [farling42/obsidian-import-json#7]
Say my CSV file is:
```
name,value
Alice,a
Bob, "b,c,d" 
```
And my template:
```
{{name}}:: [[{{value}}]] 
```
In Alice.md it returns `Alice:: a` as expected. But in Bob.md it returns `Bob:: [[ &quot;b]]`. Is it possible to have it return like this?
```
Bob:: b
Bob:: c
Bob:: d
```

**Comment by farling42** [comment]
Hi, because you have a space on the second line after the comma, it is reading the rest of the line as three more fields.
If you had:
```
name,value
Alice,a
Bob,"b,c,d"
```
Then it would end up with:
```
Bob:: [[b,c,d]]
```

Unfortunately nesting of lists isn't really possible in CSV file formats, and I'm not sure how easy it would be to implement it locally. It would have to consider quotes within quotes and other special characters that could interrupt the detection of commas within the field.

**Comment by ooker777** [comment]
I find the [csv-to-md](https://github.com/kometenstaub/csv-to-md "") script work like a charm. Do you think it would be best to recommend using it to other users as well?

**Comment by farling42** [comment]
> I find the [csv-to-md](https://github.com/kometenstaub/csv-to-md) script work like a charm. Do you think it would be best to recommend using it to other users as well?

How do you use that script to break up your "b,c,d" single value?

**Comment by ooker777** [comment]
not really (see [this issue](https://github.com/kometenstaub/csv-to-md/issues/13#issuecomment-1064276086 "FR: for multiple-value cells, make an option to have multiple lines of the same key instead of one key with multiple values · Issue #13 · kometenstaub/csv-to-md")). But it can make it to
```
Bob:: [[b]] [[c]] [[d]] 
```
and from there you can use regex to split it into multiple lines
